import { motion } from "motion/react";
import { Shield, FileText, Scale, Info, CheckCircle2 } from "lucide-react";

export default function LegalPage({ type }: { type: 'terms' | 'privacy' | 'refund' | 'disclaimer' }) {
  const content = {
    terms: {
      title: "Terms of Service",
      icon: <Scale className="text-primary" />,
      sections: [
        {
          title: "1. Acceptance of Terms",
          content: "By accessing or using Lopa X AI, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site."
        },
        {
          title: "2. Use License",
          content: "Permission is granted to temporarily use the AI services on Lopa X AI for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title."
        },
        {
          title: "3. Content Generation",
          content: "Users are solely responsible for the prompts they provide and the resulting content generated by the AI. Lopa X AI does not claim ownership of user-generated content but reserves the right to monitor for illegal activities."
        },
        {
          title: "4. Limitations",
          content: "In no event shall Lopa X AI or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Lopa X AI."
        }
      ]
    },
    privacy: {
      title: "Privacy Policy",
      icon: <Shield className="text-emerald-500" />,
      sections: [
        {
          title: "1. Data Collection",
          content: "We collect minimal personal information required for account creation and service delivery. This includes your email address and name. We do not collect sensitive personal data without explicit consent."
        },
        {
          title: "2. Conversation Privacy",
          content: "Your conversations with our AI models are encrypted and private. We do not use your personal conversations to train global models unless you explicitly opt-in to our research program."
        },
        {
          title: "3. Third-Party Services",
          content: "We use trusted third-party providers for payment processing (Razorpay) and AI model hosting (Google, Groq). These providers have their own privacy policies governing the use of your information."
        },
        {
          title: "4. Cookies",
          content: "We use cookies to maintain your session and provide a personalized experience. You can control cookie settings through your browser, but some features may not function correctly without them."
        }
      ]
    },
    refund: {
      title: "Refund Policy",
      icon: <FileText className="text-amber-500" />,
      sections: [
        {
          title: "1. Satisfaction Guarantee",
          content: "We strive for 100% customer satisfaction. If you are not happy with our Pro or Lifetime plans, you are eligible for a full refund within 7 days of your initial purchase."
        },
        {
          title: "2. Eligibility",
          content: "To be eligible for a refund, you must have used less than 50% of your monthly credit quota. Lifetime plans are eligible for a refund if requested within the first 7 days of purchase."
        },
        {
          title: "3. Process",
          content: "To request a refund, please contact our support team at support@lopa.ai with your order details. Refunds are typically processed within 5-10 business days to your original payment method."
        },
        {
          title: "4. Exceptions",
          content: "Refunds are not provided for accounts that have been suspended due to violations of our Terms of Service or for users who have engaged in fraudulent activities."
        }
      ]
    },
    disclaimer: {
      title: "18+ Disclaimer",
      icon: <Info className="text-red-500" />,
      sections: [
        {
          title: "1. Age Restriction",
          content: "The 18+ section of Lopa X AI is strictly for users who are at least 18 years of age or the legal age of majority in their jurisdiction. Access by minors is strictly prohibited."
        },
        {
          title: "2. Content Nature",
          content: "Content in this section may include mature themes, adult language, and unrestricted AI interactions. User discretion is advised. We do not verify the factual accuracy of AI-generated adult content."
        },
        {
          title: "3. User Responsibility",
          content: "Users are responsible for ensuring that their use of the 18+ section complies with local laws. Lopa X AI is not liable for any legal consequences arising from the use of this section in restricted jurisdictions."
        }
      ]
    }
  }[type];

  return (
    <div className="max-w-4xl mx-auto py-12 space-y-12">
      <motion.div 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center gap-6"
      >
        <div className="w-20 h-20 rounded-[2rem] bg-white/5 flex items-center justify-center text-4xl shadow-2xl border border-white/10">
          {content.icon}
        </div>
        <div>
          <h1 className="text-5xl font-black tracking-tighter">{content.title}</h1>
          <p className="text-gray-500 mt-2 font-medium">Last updated: March 6, 2026</p>
        </div>
      </motion.div>
      
      <div className="space-y-8">
        {content.sections.map((section, i) => (
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.1 }}
            key={i}
            className="glass-card p-8 space-y-4 border-white/5 hover:border-white/10 transition-all"
          >
            <h3 className="text-2xl font-bold text-white flex items-center gap-3">
              <CheckCircle2 size={24} className="text-primary" />
              {section.title}
            </h3>
            <p className="text-gray-400 leading-relaxed text-lg">
              {section.content}
            </p>
          </motion.div>
        ))}
      </div>

      <div className="glass-card p-8 bg-primary/5 border-primary/20 text-center space-y-4">
        <p className="text-gray-400">Still have questions about our policies?</p>
        <button className="px-8 py-3 bg-primary text-white font-bold rounded-xl hover:scale-105 transition-all">
          Contact Support
        </button>
      </div>
    </div>
  );
}
